# Generated by Django 6.0.6 on 2026-06-15 22:10

import apps.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_event',
            field=models.DateField(validators=[apps.events.models.check_date]),
        ),
    ]
