# Generated by Django 6.0.6 on 2026-06-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_event',
            new_name='date',
        ),
    ]
