# Generated by Django 6.0.6 on 2026-06-30 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_code',
        ),
    ]
