# Generated by Django 6.0.6 on 2026-07-02 18:12

import apps.events.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_event_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='%H:%M'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(validators=[apps.events.models.check_date], verbose_name='%d/%m/%Y'),
        ),
    ]
