# Generated by Django 6.0.6 on 2026-06-25 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_price'),
        ('tickets', '0002_alter_ticket_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to='events.event'),
        ),
    ]
