# Generated by Django 6.0.6 on 2026-06-25 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_profile_image'),
        ('events', '0006_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizer_category', to='events.category'),
        ),
        migrations.AddField(
            model_name='account',
            name='organizer_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='stage_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
