# Generated by Django 6.0.6 on 2026-06-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_main_category_account_organizer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/profile_images'),
        ),
    ]
